---

- block:
    - name: 'Debian/Ubuntu | Install apt-transport-https and ca-certificates'
      apt:
        name:
          - 'apt-transport-https'
          - 'ca-certificates'
        state: 'present'
        cache_valid_time: 3600
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
    - name: 'Debian/Ubuntu | Installing repository key'
      apt_key:
        url: '{{ wazuh_repo_key }}'
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
    - name: 'Debian/Ubuntu | Add Wazuh repositories'
      apt_repository:
        repo: '{{ wazuh_repo }}'
        state: 'present'
        update_cache: true
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
  when: 'wazuh_repo_add'

- block:
    - name: 'Debian/Ubuntu | Setting webupd8 repository'
      apt_repository:
        repo: '{{ oracle_java_repo }}'
        codename: '{{ oracle_java_dist }}'
        update_cache: true
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
    - name: 'Debian/Ubuntu | Accept Oracle Java 8 license'
      debconf:
        name: '{{ oracle_java_pkg }}'
        question: 'shared/accepted-oracle-license-v1-1'
        value: true
        vtype: 'boolean'
    - name: 'Debian/Ubuntu | Oracle Java 8 installer'
      apt:
        name: '{{ oracle_java_pkg }}'
        state: 'present'
        cache_valid_time: 3600
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
  tags:
    - 'init'
  when: 'wazuh_java_install'

- block:
    - name: 'Debian/Ubuntu | Install OpenScap'
      apt:
        name:
          - 'libopenscap8'
          - 'xsltproc'
        state: 'present'
        cache_valid_time: 3600
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
      tags:
        - 'init'
    - name: 'Debian/Ubuntu | Check OpenScap installed version'
      shell: "dpkg --compare-versions \"$(dpkg-query --showformat='${Version}' --show libopenscap8)\" \">=\" \"1.2\"; echo $?"
      register: 'wazuh_openscap_version_check'
      changed_when: false
      tags:
        - 'config'
    - name: 'Debian/Ubuntu | Register OpenScap version check result'
      set_fact:
        wazuh_openscap_version_valid: '{{ wazuh_openscap_version_check.stdout == "0" }}'
      changed_when: false
      tags:
        - 'config'
  when: 'wazuh_openscap_enabled|default(false)'
