---

- name: 'Include os vars.'
  include_vars:
    dir: 'os'
    files_matching: "({{ ansible_system }}|{{ ansible_os_family }})\
                     (_{{ ansible_distribution }})?\
                     (_{{ ansible_distribution_major_version }})?.yml"

- name: 'Pre-installation check.'
  block:

    - name: 'Check whether wazuh-agent is installed.'
      check_mode: true
      ignore_errors: true
      package:
        name: 'wazuh-agent'
        state: 'present'
      register: 'wazuh_agent_package'

    - name: 'Purge /var/ossec directory before installation.'
      file:
        path: '/var/ossec'  # TODO: purge packages owning this directory, if any.
        state: 'absent'
      when: 'wazuh_agent_package is failed
          or wazuh_agent_package is changed'

  when: 'wazuh_purge'

- name: 'Check certain ossec_config settings.'
  block:
    - name: 'Check whether certain wodles are enabled.'
      include_tasks: 'check_wodle.yml'
      loop: '{{ [ossec_config.wodle|default([])]|flatten }}'
      loop_control:
        loop_var: 'wazuh_wodle'
  vars:
    ossec_config: '{{ wazuh_agent.ossec_config }}'
  when:
    - '"ossec_config" in wazuh_agent'

- include_tasks: "Windows.yml"
  when: 'ansible_os_family == "Windows"'

- include_tasks: "Linux.yml"
  when: 'ansible_system == "Linux"'
