---

- name: 'RedHat/CentOS/Fedora | Install Wazuh repo'
  yum_repository:
    name: 'wazuh_repo'
    description: 'Wazuh repository'
    baseurl: '{{ wazuh_repo_url }}'
    gpgkey: '{{ wazuh_repo_key }}'
    gpgcheck: true
  when:
    - 'wazuh_repo_add'
    - 'wazuh_repo is defined'
    - 'wazuh_repo_key is defined'

- block:
    - name: 'RedHat/CentOS/Fedora | download Oracle Java RPM'
      async: '{{ wazuh_async_timeout }}'
      get_url:
        url: '{{ oracle_java_rpm }}'
        dest: '{{ oracle_java_rpm|basename }}'
        headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
      poll: '{{ wazuh_async_poll }}'
    - name: 'RedHat/CentOS/Fedora | Install Oracle Java RPM'
      async: '{{ wazuh_async_timeout }}'
      package:
        name: '/tmp/{{ oracle_java_rpm|basename }}'
        state: 'present'
      poll: '{{ wazuh_async_poll }}'
      when:
        - 'oracle_java_task_rpm_download is defined'
        - 'oracle_java_task_rpm_download.finished'
  tags:
    - 'init'
  when: 'wazuh_java_install'

- name: 'RedHat/CentOS/RedHat | Install openscap'
  async: '{{ wazuh_async_timeout }}'
  package:
    name: 'openscap-scanner'
    state: 'present'
  poll: '{{ wazuh_async_poll }}'
  tags:
    - 'init'
  when: 'wazuh_openscap_enabled|default(false)'
